export const movies = [
  // ACTION
  {
    id: 1,
    title: "Mad Max: Fury Road",
    genre: "Action",
    description: "A post-apocalyptic warrior helps prisoners escape a tyrant.",
    poster_path: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 2,
    title: "John Wick",
    genre: "Action",
    description: "A retired hitman seeks vengeance.",
    poster_path: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 3,
    title: "The Dark Knight",
    genre: "Action",
    description: "Batman faces the Joker in Gotham.",
    poster_path: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 4,
    title: "Top Gun: Maverick",
    genre: "Action",
    description: "A pilot trains the next generation.",
    poster_path: "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
    video: "/videos/kids1.mp4",
  },

  // DRAMA
  {
    id: 5,
    title: "Shawshank Redemption",
    genre: "Drama",
    description: "Friendship and hope inside a prison.",
    poster_path: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 6,
    title: "Forrest Gump",
    genre: "Drama",
    description: "Life story of a simple man.",
    poster_path: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 7,
    title: "Schindler's List",
    genre: "Drama",
    description: "Saving lives during war.",
    poster_path: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 8,
    title: "The Godfather",
    genre: "Drama",
    description: "Story of a crime family.",
    poster_path: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmfw5J.jpg",
    video: "/videos/kids1.mp4",
  },

  // KIDS
  {
    id: 9,
    title: "The Lion King",
    genre: "Kids",
    description: "A lion prince finds his destiny.",
    poster_path: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 10,
    title: "Toy Story",
    genre: "Kids",
    description: "Toys come to life.",
    poster_path: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 11,
    title: "Finding Nemo",
    genre: "Kids",
    description: "A fish searches for his son.",
    poster_path: "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 12,
    title: "Moana",
    genre: "Kids",
    description: "A girl sails to save her people.",
    poster_path: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjU3NDU2MDI@._V1_SX300.jpg",
    video: "/videos/kids1.mp4",
  },

  // THRILLER
  {
    id: 13,
    title: "Inception",
    genre: "Thriller",
    description: "Dreams inside dreams.",
    poster_path: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 14,
    title: "Gone Girl",
    genre: "Thriller",
    description: "A missing wife mystery.",
    poster_path: "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 15,
    title: "Parasite",
    genre: "Thriller",
    description: "A poor family enters a rich house.",
    poster_path: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    video: "/videos/kids1.mp4",
  },
  {
    id: 16,
    title: "Se7en",
    genre: "Thriller",
    description: "Detectives chase a serial killer.",
    poster_path: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    video: "/videos/kids1.mp4",
  },
];